### PR TITLE
Adding $id

### LINKED ISSUE #2: Add a `$id`
The schema should have an `$id` property to be able to refer to it.

### PR DESCRIPTION
**Pull request by santosomar**
Fixes #2

### CODE REVIEW

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
Thank you for the update. Unfortunately, it also changed a few other things, which I guess should be discussed in detail.

**Comment by santosomar** [comment]
Thank you @tschmidtb51 !!

**Comment by tschmidtb51** [comment]
> Thank you for the update. Unfortunately, it also changed a few other things, which I guess should be discussed in detail. I'll provide an alternative PR later today.

See #7 as a replacement. General clean up will be done in the next PR.

**Comment by santosomar** [comment]
Addressed in #7

**Pull request closed without merging**
